// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "pheet-fiber-backend/models"
)

// IFileUsecase is an autogenerated mock type for the IFileUsecase type
type IFileUsecase struct {
	mock.Mock
}

// DeleteOnGCP provides a mock function with given fields: req
func (_m *IFileUsecase) DeleteOnGCP(req []*models.DeleteFileReq) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOnGCP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*models.DeleteFileReq) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadToGCP provides a mock function with given fields: ctx, fileReq
func (_m *IFileUsecase) UploadToGCP(ctx context.Context, fileReq []*models.FileReq) ([]*models.FileResp, error) {
	ret := _m.Called(ctx, fileReq)

	if len(ret) == 0 {
		panic("no return value specified for UploadToGCP")
	}

	var r0 []*models.FileResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.FileReq) ([]*models.FileResp, error)); ok {
		return rf(ctx, fileReq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*models.FileReq) []*models.FileResp); ok {
		r0 = rf(ctx, fileReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FileResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*models.FileReq) error); ok {
		r1 = rf(ctx, fileReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIFileUsecase creates a new instance of IFileUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIFileUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IFileUsecase {
	mock := &IFileUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
