// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	helper "github.com/Pheethy/psql/helper"
	mock "github.com/stretchr/testify/mock"

	models "pheet-fiber-backend/models"

	sync "sync"

	uuid "github.com/gofrs/uuid"
)

// IProductsRepositoryDB is an autogenerated mock type for the IProductsRepositoryDB type
type IProductsRepositoryDB struct {
	mock.Mock
}

// CraeteProduct provides a mock function with given fields: ctx, req
func (_m *IProductsRepositoryDB) CraeteProduct(ctx context.Context, req *models.Products) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CraeteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Products) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteImages provides a mock function with given fields: ctx, ids
func (_m *IProductsRepositoryDB) DeleteImages(ctx context.Context, ids []*uuid.UUID) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*uuid.UUID) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProduct provides a mock function with given fields: ctx, product
func (_m *IProductsRepositoryDB) DeleteProduct(ctx context.Context, product *models.Products) error {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Products) error); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchAllProducts provides a mock function with given fields: ctx, args, paginator
func (_m *IProductsRepositoryDB) FetchAllProducts(ctx context.Context, args *sync.Map, paginator *helper.Paginator) ([]*models.Products, error) {
	ret := _m.Called(ctx, args, paginator)

	if len(ret) == 0 {
		panic("no return value specified for FetchAllProducts")
	}

	var r0 []*models.Products
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sync.Map, *helper.Paginator) ([]*models.Products, error)); ok {
		return rf(ctx, args, paginator)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sync.Map, *helper.Paginator) []*models.Products); ok {
		r0 = rf(ctx, args, paginator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Products)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sync.Map, *helper.Paginator) error); ok {
		r1 = rf(ctx, args, paginator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchOneProduct provides a mock function with given fields: ctx, productId
func (_m *IProductsRepositoryDB) FetchOneProduct(ctx context.Context, productId *uuid.UUID) (*models.Products, error) {
	ret := _m.Called(ctx, productId)

	if len(ret) == 0 {
		panic("no return value specified for FetchOneProduct")
	}

	var r0 *models.Products
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) (*models.Products, error)); ok {
		return rf(ctx, productId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) *models.Products); ok {
		r0 = rf(ctx, productId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Products)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID) error); ok {
		r1 = rf(ctx, productId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduct provides a mock function with given fields: ctx, req
func (_m *IProductsRepositoryDB) UpdateProduct(ctx context.Context, req *models.Products) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Products) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIProductsRepositoryDB creates a new instance of IProductsRepositoryDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProductsRepositoryDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProductsRepositoryDB {
	mock := &IProductsRepositoryDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
