// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IProductsHandlers is an autogenerated mock type for the IProductsHandlers type
type IProductsHandlers struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *IProductsHandlers) Create(c *gin.Context) {
	_m.Called(c)
}

// DeleteProduct provides a mock function with given fields: c
func (_m *IProductsHandlers) DeleteProduct(c *gin.Context) {
	_m.Called(c)
}

// FetchAllProduct provides a mock function with given fields: c
func (_m *IProductsHandlers) FetchAllProduct(c *gin.Context) {
	_m.Called(c)
}

// FetchOneProduct provides a mock function with given fields: c
func (_m *IProductsHandlers) FetchOneProduct(c *gin.Context) {
	_m.Called(c)
}

// UpdateProduct provides a mock function with given fields: c
func (_m *IProductsHandlers) UpdateProduct(c *gin.Context) {
	_m.Called(c)
}

// NewIProductsHandlers creates a new instance of IProductsHandlers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProductsHandlers(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProductsHandlers {
	mock := &IProductsHandlers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
